### ISSUE TITLE
数据、代码、模型什么时候可以看到呢？

### ISSUE THREAD

**Issue by murray-z** [williamliujl/Qilin-Med#1]
数据、代码、模型什么时候可以看到呢？

**Comment by yeeeqichen** [comment]
Hi,

Thanks for your attention! Sorry for the late response. 
Since we have some concurrent works to deal with these days, the data and the trained-models still need some time to be released after proper arrangement. It won't take long and please stay tuned.  We've just released the codes and feel free to contact us if you have any questions about it.

Best
